---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ./plex_config:/config
      - /media/BigData/Media/Series:/data/tvshows
      - /media/BigData/Media/Movies:/data/movies
      - /media/BigData/Media/Music:/data/music
      - /media/BigData/Media/Pictures:/data/pictures
    restart: unless-stopped
